name: Retail Banking Quality Hub

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME service parameter (leave blank)
        required: false
      RELEASE:
        description: Release
        required: false
        default: 33.3.1
      BROWSER:
        description: Browser
        required: false
        default: Chrome
      OS:
        description: OS
        required: false
        default: macOS
      TEST_PATH:
        description: Test path to run
        required: false
        default: tests/unit

env:
  ALLURE_ENDPOINT: https://demo.testops.cloud
  ALLURE_PROJECT_ID: 4601
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: allure-results
  ALLURE_LAUNCH_NAME: retail-banking-quality-hub-demo
  ALLURE_LAUNCH_TAGS: unit, github

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://demo.testops.cloud/
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 4601

      - name: Run pytest tests
        run: |
          allurectl watch -- pytest ${{ github.event.inputs.TEST_PATH }} --alluredir="${ALLURE_RESULTS}"
        env:
          BROWSER: ${{ github.event.inputs.BROWSER }}
          OS: ${{ github.event.inputs.OS }}